# Generated by Django 5.1.2 on 2024-11-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop_app', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawneditem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pawned_items', to='pawnshop_app.client'),
        ),
        migrations.AlterField(
            model_name='pawneditem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
